name: Full Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  jobs:
    build-and-deploy-backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            path: backend

       - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn -f backend/pom.xml clean package

      - name: Run tests
        run: mvn -f backend/pom.xml test

      - name: Deploy
        # Add your deployment commands here


    build-and-deploy-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            path: frontend

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.x'

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy
          # Add your deployment commands here